spring.application.name=visualizarTarefas

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://35.198.58.59:3306/gsw_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:chronosapi}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Bolsonaro#22}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

server.port=${SERVER_PORT:8099}

profissionais.api.url=${PROFISSIONAIS_API_URL}

#spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
#spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
#spring.cache.type=${SPRING_CACHE_TYPE:redis}